# Profile Enhancement Merge Template for Clash Verge

profile:
  store-selected: true

proxy-groups:
  - name: Без Proxy
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bypass.png
    type: select
    hidden: true
    proxies:
      - DIRECT
  - name: Discord
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    type: select
    proxies:
      - Proxy
      - Без Proxy
  - name: YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies:
      - Proxy
      - Без Proxy
  - name: Games
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    type: select
    proxies:
      - Proxy
      - Без Proxy

rule-providers:
  local_example:
    type: file
    path: ./rule-sets/local/example.yaml
    behavior: classical
    format: yaml
  category-ru:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/category-ru.mrs
    path: ./rule-sets/category-ru.mrs
    interval: 86400
  whitelist:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/whitelist.mrs
    path: ./rule-sets/whitelist.mrs
    interval: 86400
  direct-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geoip/release/mihomo/direct.mrs
    path: ./rule-sets/direct-ips.mrs
    interval: 86400
  ru-apps:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/legiz-ru/mihomo-rule-sets/main/other/ru-app-list.yaml
    path: ./rule-sets/ru-apps.yaml
    interval: 86400
  google-play:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/google-play.mrs
    path: ./rule-sets/google-play.mrs
    interval: 86400
  apple:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/apple.mrs
    path: ./rule-sets/apple.mrs
    interval: 86400
  microsoft:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/microsoft.mrs
    path: ./rule-sets/microsoft.mrs
    interval: 86400
  youtube:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/youtube.mrs
    path: ./rule-sets/youtube.mrs
    interval: 86400
  twitch:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/twitch.mrs
    path: ./rule-sets/twitch.mrs
    interval: 86400
  twitch-ads:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/twitch-ads.mrs
    path: ./rule-sets/twitch-ads.mrs
    interval: 86400
  private-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/private.mrs
    path: ./rule-sets/geosite-private.mrs
    interval: 86400
  private-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geoip/release/mihomo/private.mrs
    path: ./rule-sets/geoip-private.mrs
    interval: 86400
  discord_domains:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/discord.mrs
    path: ./rule-sets/discord_domains.mrs
    interval: 86400
  discord_voiceips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/legiz-ru/mihomo-rule-sets/main/other/discord-voice-ip-list.mrs
    path: ./rule-sets/discord_voiceips.mrs
    interval: 86400
  discord_vc:
    type: http
    path: ./rule-sets/discord_vc.yaml
    url: https://raw.githubusercontent.com/Shaldown/Clash-Verge-rev-configuration/refs/heads/main/rule-sets/discord_vc.yaml
    behavior: classical
    format: yaml
  torrent-trackers:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-trackers.mrs
    path: ./rule-sets/torrent-trackers.mrs
    interval: 86400
  torrent-clients:
    type: http
    behavior: classical
    format: yaml
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-clients.yaml
    path: ./rule-sets/torrent-clients.yaml
    interval: 86400
  games:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/roscomvpn/custom-category/release/mihomo/games.yaml
    path: ./rule-sets/games.yaml
    interval: 86400
  steam:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/steam.mrs
    path: ./rule-sets/steam.mrs
    interval: 86400
  epicgames:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/epicgames.mrs
    path: ./rule-sets/epicgames.mrs
    interval: 86400
  pinterest:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/pinterest.mrs
    path: ./rule-sets/pinterest.mrs
    interval: 86400
  quic:
    type: http
    path: ./rule-sets/quic.yaml
    url: https://raw.githubusercontent.com/Shaldown/Clash-Verge-rev-configuration/refs/heads/main/rule-sets/quic.yaml
    behavior: classical
    format: yaml
    interval: 86400

rules:
  # Локальная сеть
  - RULE-SET,private-domains,DIRECT
  - RULE-SET,private-ips,DIRECT,no-resolve

  # Торренты
  - RULE-SET,torrent-clients,DIRECT
  - RULE-SET,torrent-trackers,DIRECT
  - PROCESS-NAME-REGEX,(?i).*torrent.*,DIRECT

  # Игры
  - RULE-SET,games,Games
  - RULE-SET,steam,Games
  - RULE-SET,epicgames,Games

  # Блокировка QUIC (для VLESS Reality)
  - RULE-SET,quic,REJECT

  # YouTube
  - RULE-SET,youtube,YouTube
  - PROCESS-NAME-REGEX,(?i).*youtube.*,YouTube

  # Twitch
  - RULE-SET,twitch-ads,Proxy
  - RULE-SET,twitch,Без Proxy

  # Discord
  - AND,((NETWORK,udp),(DST-PORT,19200-19500)),Discord
  - AND,((RULE-SET,discord_voiceips),(NETWORK,udp),(DST-PORT,50000-50100)),Discord
  - RULE-SET,discord_vc,Discord
  - RULE-SET,discord_domains,Discord
  - PROCESS-NAME-REGEX,(?i).*discord.*,Discord

  # Обновления и пуши
  - RULE-SET,google-play,Без Proxy
  - RULE-SET,apple,Без Proxy
  - RULE-SET,microsoft,Без Proxy

  # Блокировка реклама Pinteres
  - RULE-SET,pinterest,Без Proxy

  # СНГ сервисы
  - RULE-SET,category-ru,Без Proxy
  - RULE-SET,whitelist,Без Proxy
  - RULE-SET,ru-apps,Без Proxy
  - RULE-SET,direct-ips,Без Proxy,no-resolve

  - MATCH, Proxy
