# Profile Enhancement Merge Template for Clash Verge

profile:
  store-selected: true

rule-providers:
  local_example:
    type: file
    path: ./rule-sets/local/example.yaml
    behavior: classical
    format: yaml

rules:
  # Дополнения правил
  - RULE-SET,local_example,Без Proxy